/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the homepage.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * Mono label above title.
             */
            eyebrow?: string | null;
            title: string;
            subtitle?: string | null;
            actions?:
              | {
                  link?: {
                    type?: ('internal' | 'external') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    url?: string | null;
                    label?: string | null;
                    appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            /**
             * External image URL (e.g. Unsplash). Overrides uploaded image if set.
             */
            imageUrl?: string | null;
            /**
             * Mono caption displayed over/under the image.
             */
            imageCaption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSplit';
          }
        | {
            /**
             * Top-left mono label (e.g. "CASE · 014 / LEAD ROUTING").
             */
            eyebrow?: string | null;
            /**
             * Top-right mono label (e.g. "2026.Q1").
             */
            meta?: string | null;
            /**
             * Large hazard-size number (e.g. "28×").
             */
            statValue?: string | null;
            description: string;
            /**
             * Full-bleed background image (DS filters applied).
             */
            background?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            backgroundUrl?: string | null;
            tags?:
              | {
                  icon?:
                    | (
                        | 'arrow-right'
                        | 'arrow-up-right'
                        | 'arrow-down'
                        | 'plus'
                        | 'minus'
                        | 'x'
                        | 'check'
                        | 'chevron-down'
                        | 'chevron-right'
                        | 'chevron-left'
                        | 'menu'
                        | 'search'
                        | 'external'
                        | 'mail'
                        | 'phone'
                        | 'map-pin'
                        | 'clock'
                        | 'calendar'
                        | 'user'
                        | 'users'
                        | 'file'
                        | 'file-text'
                        | 'folder'
                        | 'code'
                        | 'terminal'
                        | 'git-branch'
                        | 'zap'
                        | 'cpu'
                        | 'database'
                        | 'server'
                        | 'plug'
                        | 'box'
                        | 'layers'
                        | 'grid'
                        | 'layout'
                        | 'sparkles'
                        | 'bot'
                        | 'message'
                        | 'bell'
                        | 'shield'
                        | 'lock'
                        | 'star'
                        | 'trending-up'
                        | 'bar-chart'
                        | 'pie-chart'
                        | 'compass'
                        | 'settings'
                        | 'play'
                        | 'pause'
                        | 'refresh'
                        | 'download'
                        | 'upload'
                        | 'target'
                        | 'flag'
                        | 'link'
                        | 'copy'
                        | 'github'
                        | 'filter'
                        | 'more'
                        | 'alert'
                        | 'info'
                        | 'eye'
                      )
                    | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroFullbleed';
          }
        | {
            /**
             * e.g. "SECTION 01". Shown in orange mono.
             */
            number?: string | null;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionHead';
          }
        | {
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  icon?:
                    | (
                        | 'arrow-right'
                        | 'arrow-up-right'
                        | 'arrow-down'
                        | 'plus'
                        | 'minus'
                        | 'x'
                        | 'check'
                        | 'chevron-down'
                        | 'chevron-right'
                        | 'chevron-left'
                        | 'menu'
                        | 'search'
                        | 'external'
                        | 'mail'
                        | 'phone'
                        | 'map-pin'
                        | 'clock'
                        | 'calendar'
                        | 'user'
                        | 'users'
                        | 'file'
                        | 'file-text'
                        | 'folder'
                        | 'code'
                        | 'terminal'
                        | 'git-branch'
                        | 'zap'
                        | 'cpu'
                        | 'database'
                        | 'server'
                        | 'plug'
                        | 'box'
                        | 'layers'
                        | 'grid'
                        | 'layout'
                        | 'sparkles'
                        | 'bot'
                        | 'message'
                        | 'bell'
                        | 'shield'
                        | 'lock'
                        | 'star'
                        | 'trending-up'
                        | 'bar-chart'
                        | 'pie-chart'
                        | 'compass'
                        | 'settings'
                        | 'play'
                        | 'pause'
                        | 'refresh'
                        | 'download'
                        | 'upload'
                        | 'target'
                        | 'flag'
                        | 'link'
                        | 'copy'
                        | 'github'
                        | 'filter'
                        | 'more'
                        | 'alert'
                        | 'info'
                        | 'eye'
                      )
                    | null;
                  image?: (number | null) | Media;
                  /**
                   * External image URL (overrides upload).
                   */
                  imageUrl?: string | null;
                  /**
                   * Optional badge over image (mono label).
                   */
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * Optional deep-link to service detail page.
                   */
                  linkedService?: (number | null) | Service;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            items?:
              | {
                  /**
                   * e.g. "99.8%", "24/7", "1.2s".
                   */
                  value: string;
                  label: string;
                  sublabel?: string | null;
                  /**
                   * Render value in hazard orange. First item defaults to accent if unset.
                   */
                  accent?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numbers';
          }
        | {
            steps?:
              | {
                  /**
                   * e.g. "01". Auto-generated if empty.
                   */
                  number?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processTimeline';
          }
        | {
            imageSide?: ('right' | 'left') | null;
            eyebrow?: string | null;
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            action?: {
              link?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
                appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
              };
            };
            image?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitLayout';
          }
        | {
            /**
             * Top mono-label in the content column.
             */
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            /**
             * Bottom mono-line (e.g. "— EST. 2025 · US + IL").
             */
            footnote?: string | null;
            /**
             * Image shown in the right column.
             */
            image?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accentBlock';
          }
        | {
            plans?:
              | {
                  name: string;
                  /**
                   * Raw text, e.g. "$2,400".
                   */
                  price: string;
                  /**
                   * e.g. "per month".
                   */
                  priceSub?: string | null;
                  /**
                   * Highlighted plan (elevated surface + badge).
                   */
                  hot?: boolean | null;
                  badge?: string | null;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  cta?: {
                    link?: {
                      type?: ('internal' | 'external') | null;
                      newTab?: boolean | null;
                      reference?: {
                        relationTo: 'pages';
                        value: number | Page;
                      } | null;
                      url?: string | null;
                      label?: string | null;
                      appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
                    };
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingGrid';
          }
        | {
            /**
             * Left mono-label in the header.
             */
            heading?: string | null;
            /**
             * Optional right mono-label (e.g. "38 TEAMS · GROWING").
             */
            meta?: string | null;
            logos?:
              | {
                  name: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marquee';
          }
        | {
            /**
             * e.g. "TESTIMONIAL / 007".
             */
            eyebrow?: string | null;
            quote: string;
            name: string;
            role?: string | null;
            /**
             * Portrait (left column). Omit for stacked variant.
             */
            image?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionFaq';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Orange background. Uncheck for dark surface.
             */
            accent?: boolean | null;
            eyebrow?: string | null;
            title: string;
            action?: {
              link?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
                appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
              };
            };
            contacts?:
              | {
                  icon?:
                    | (
                        | 'arrow-right'
                        | 'arrow-up-right'
                        | 'arrow-down'
                        | 'plus'
                        | 'minus'
                        | 'x'
                        | 'check'
                        | 'chevron-down'
                        | 'chevron-right'
                        | 'chevron-left'
                        | 'menu'
                        | 'search'
                        | 'external'
                        | 'mail'
                        | 'phone'
                        | 'map-pin'
                        | 'clock'
                        | 'calendar'
                        | 'user'
                        | 'users'
                        | 'file'
                        | 'file-text'
                        | 'folder'
                        | 'code'
                        | 'terminal'
                        | 'git-branch'
                        | 'zap'
                        | 'cpu'
                        | 'database'
                        | 'server'
                        | 'plug'
                        | 'box'
                        | 'layers'
                        | 'grid'
                        | 'layout'
                        | 'sparkles'
                        | 'bot'
                        | 'message'
                        | 'bell'
                        | 'shield'
                        | 'lock'
                        | 'star'
                        | 'trending-up'
                        | 'bar-chart'
                        | 'pie-chart'
                        | 'compass'
                        | 'settings'
                        | 'play'
                        | 'pause'
                        | 'refresh'
                        | 'download'
                        | 'upload'
                        | 'target'
                        | 'flag'
                        | 'link'
                        | 'copy'
                        | 'github'
                        | 'filter'
                        | 'more'
                        | 'alert'
                        | 'info'
                        | 'eye'
                      )
                    | null;
                  /**
                   * e.g. "HELLO@GREPFOX.CO".
                   */
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
      )[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Shown in cards and grids.
   */
  summary?: string | null;
  icon?:
    | (
        | 'arrow-right'
        | 'arrow-up-right'
        | 'arrow-down'
        | 'plus'
        | 'minus'
        | 'x'
        | 'check'
        | 'chevron-down'
        | 'chevron-right'
        | 'chevron-left'
        | 'menu'
        | 'search'
        | 'external'
        | 'mail'
        | 'phone'
        | 'map-pin'
        | 'clock'
        | 'calendar'
        | 'user'
        | 'users'
        | 'file'
        | 'file-text'
        | 'folder'
        | 'code'
        | 'terminal'
        | 'git-branch'
        | 'zap'
        | 'cpu'
        | 'database'
        | 'server'
        | 'plug'
        | 'box'
        | 'layers'
        | 'grid'
        | 'layout'
        | 'sparkles'
        | 'bot'
        | 'message'
        | 'bell'
        | 'shield'
        | 'lock'
        | 'star'
        | 'trending-up'
        | 'bar-chart'
        | 'pie-chart'
        | 'compass'
        | 'settings'
        | 'play'
        | 'pause'
        | 'refresh'
        | 'download'
        | 'upload'
        | 'target'
        | 'flag'
        | 'link'
        | 'copy'
        | 'github'
        | 'filter'
        | 'more'
        | 'alert'
        | 'info'
        | 'eye'
      )
    | null;
  tier?: ('core' | 'pro' | 'enterprise') | null;
  heroImage?: (number | null) | Media;
  /**
   * External hero image URL.
   */
  heroImageUrl?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | {
            /**
             * Mono label above title.
             */
            eyebrow?: string | null;
            title: string;
            subtitle?: string | null;
            actions?:
              | {
                  link?: {
                    type?: ('internal' | 'external') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                    url?: string | null;
                    label?: string | null;
                    appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            /**
             * External image URL (e.g. Unsplash). Overrides uploaded image if set.
             */
            imageUrl?: string | null;
            /**
             * Mono caption displayed over/under the image.
             */
            imageCaption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSplit';
          }
        | {
            /**
             * Top-left mono label (e.g. "CASE · 014 / LEAD ROUTING").
             */
            eyebrow?: string | null;
            /**
             * Top-right mono label (e.g. "2026.Q1").
             */
            meta?: string | null;
            /**
             * Large hazard-size number (e.g. "28×").
             */
            statValue?: string | null;
            description: string;
            /**
             * Full-bleed background image (DS filters applied).
             */
            background?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            backgroundUrl?: string | null;
            tags?:
              | {
                  icon?:
                    | (
                        | 'arrow-right'
                        | 'arrow-up-right'
                        | 'arrow-down'
                        | 'plus'
                        | 'minus'
                        | 'x'
                        | 'check'
                        | 'chevron-down'
                        | 'chevron-right'
                        | 'chevron-left'
                        | 'menu'
                        | 'search'
                        | 'external'
                        | 'mail'
                        | 'phone'
                        | 'map-pin'
                        | 'clock'
                        | 'calendar'
                        | 'user'
                        | 'users'
                        | 'file'
                        | 'file-text'
                        | 'folder'
                        | 'code'
                        | 'terminal'
                        | 'git-branch'
                        | 'zap'
                        | 'cpu'
                        | 'database'
                        | 'server'
                        | 'plug'
                        | 'box'
                        | 'layers'
                        | 'grid'
                        | 'layout'
                        | 'sparkles'
                        | 'bot'
                        | 'message'
                        | 'bell'
                        | 'shield'
                        | 'lock'
                        | 'star'
                        | 'trending-up'
                        | 'bar-chart'
                        | 'pie-chart'
                        | 'compass'
                        | 'settings'
                        | 'play'
                        | 'pause'
                        | 'refresh'
                        | 'download'
                        | 'upload'
                        | 'target'
                        | 'flag'
                        | 'link'
                        | 'copy'
                        | 'github'
                        | 'filter'
                        | 'more'
                        | 'alert'
                        | 'info'
                        | 'eye'
                      )
                    | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroFullbleed';
          }
        | {
            /**
             * e.g. "SECTION 01". Shown in orange mono.
             */
            number?: string | null;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectionHead';
          }
        | {
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  icon?:
                    | (
                        | 'arrow-right'
                        | 'arrow-up-right'
                        | 'arrow-down'
                        | 'plus'
                        | 'minus'
                        | 'x'
                        | 'check'
                        | 'chevron-down'
                        | 'chevron-right'
                        | 'chevron-left'
                        | 'menu'
                        | 'search'
                        | 'external'
                        | 'mail'
                        | 'phone'
                        | 'map-pin'
                        | 'clock'
                        | 'calendar'
                        | 'user'
                        | 'users'
                        | 'file'
                        | 'file-text'
                        | 'folder'
                        | 'code'
                        | 'terminal'
                        | 'git-branch'
                        | 'zap'
                        | 'cpu'
                        | 'database'
                        | 'server'
                        | 'plug'
                        | 'box'
                        | 'layers'
                        | 'grid'
                        | 'layout'
                        | 'sparkles'
                        | 'bot'
                        | 'message'
                        | 'bell'
                        | 'shield'
                        | 'lock'
                        | 'star'
                        | 'trending-up'
                        | 'bar-chart'
                        | 'pie-chart'
                        | 'compass'
                        | 'settings'
                        | 'play'
                        | 'pause'
                        | 'refresh'
                        | 'download'
                        | 'upload'
                        | 'target'
                        | 'flag'
                        | 'link'
                        | 'copy'
                        | 'github'
                        | 'filter'
                        | 'more'
                        | 'alert'
                        | 'info'
                        | 'eye'
                      )
                    | null;
                  image?: (number | null) | Media;
                  /**
                   * External image URL (overrides upload).
                   */
                  imageUrl?: string | null;
                  /**
                   * Optional badge over image (mono label).
                   */
                  tag?: string | null;
                  title: string;
                  description?: string | null;
                  /**
                   * Optional deep-link to service detail page.
                   */
                  linkedService?: (number | null) | Service;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            items?:
              | {
                  /**
                   * e.g. "99.8%", "24/7", "1.2s".
                   */
                  value: string;
                  label: string;
                  sublabel?: string | null;
                  /**
                   * Render value in hazard orange. First item defaults to accent if unset.
                   */
                  accent?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numbers';
          }
        | {
            steps?:
              | {
                  /**
                   * e.g. "01". Auto-generated if empty.
                   */
                  number?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processTimeline';
          }
        | {
            imageSide?: ('right' | 'left') | null;
            eyebrow?: string | null;
            title: string;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            action?: {
              link?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
                appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
              };
            };
            image?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitLayout';
          }
        | {
            /**
             * Top mono-label in the content column.
             */
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            /**
             * Bottom mono-line (e.g. "— EST. 2025 · US + IL").
             */
            footnote?: string | null;
            /**
             * Image shown in the right column.
             */
            image?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accentBlock';
          }
        | {
            plans?:
              | {
                  name: string;
                  /**
                   * Raw text, e.g. "$2,400".
                   */
                  price: string;
                  /**
                   * e.g. "per month".
                   */
                  priceSub?: string | null;
                  /**
                   * Highlighted plan (elevated surface + badge).
                   */
                  hot?: boolean | null;
                  badge?: string | null;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  cta?: {
                    link?: {
                      type?: ('internal' | 'external') | null;
                      newTab?: boolean | null;
                      reference?: {
                        relationTo: 'pages';
                        value: number | Page;
                      } | null;
                      url?: string | null;
                      label?: string | null;
                      appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
                    };
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingGrid';
          }
        | {
            /**
             * Left mono-label in the header.
             */
            heading?: string | null;
            /**
             * Optional right mono-label (e.g. "38 TEAMS · GROWING").
             */
            meta?: string | null;
            logos?:
              | {
                  name: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'marquee';
          }
        | {
            /**
             * e.g. "TESTIMONIAL / 007".
             */
            eyebrow?: string | null;
            quote: string;
            name: string;
            role?: string | null;
            /**
             * Portrait (left column). Omit for stacked variant.
             */
            image?: (number | null) | Media;
            /**
             * External image URL (overrides upload).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial';
          }
        | {
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionFaq';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Orange background. Uncheck for dark surface.
             */
            accent?: boolean | null;
            eyebrow?: string | null;
            title: string;
            action?: {
              link?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
                appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
              };
            };
            contacts?:
              | {
                  icon?:
                    | (
                        | 'arrow-right'
                        | 'arrow-up-right'
                        | 'arrow-down'
                        | 'plus'
                        | 'minus'
                        | 'x'
                        | 'check'
                        | 'chevron-down'
                        | 'chevron-right'
                        | 'chevron-left'
                        | 'menu'
                        | 'search'
                        | 'external'
                        | 'mail'
                        | 'phone'
                        | 'map-pin'
                        | 'clock'
                        | 'calendar'
                        | 'user'
                        | 'users'
                        | 'file'
                        | 'file-text'
                        | 'folder'
                        | 'code'
                        | 'terminal'
                        | 'git-branch'
                        | 'zap'
                        | 'cpu'
                        | 'database'
                        | 'server'
                        | 'plug'
                        | 'box'
                        | 'layers'
                        | 'grid'
                        | 'layout'
                        | 'sparkles'
                        | 'bot'
                        | 'message'
                        | 'bell'
                        | 'shield'
                        | 'lock'
                        | 'star'
                        | 'trending-up'
                        | 'bar-chart'
                        | 'pie-chart'
                        | 'compass'
                        | 'settings'
                        | 'play'
                        | 'pause'
                        | 'refresh'
                        | 'download'
                        | 'upload'
                        | 'target'
                        | 'flag'
                        | 'link'
                        | 'copy'
                        | 'github'
                        | 'filter'
                        | 'more'
                        | 'alert'
                        | 'info'
                        | 'eye'
                      )
                    | null;
                  /**
                   * e.g. "HELLO@GREPFOX.CO".
                   */
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroSplit?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actions?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              image?: T;
              imageUrl?: T;
              imageCaption?: T;
              id?: T;
              blockName?: T;
            };
        heroFullbleed?:
          | T
          | {
              eyebrow?: T;
              meta?: T;
              statValue?: T;
              description?: T;
              background?: T;
              backgroundUrl?: T;
              tags?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sectionHead?:
          | T
          | {
              number?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    image?: T;
                    imageUrl?: T;
                    tag?: T;
                    title?: T;
                    description?: T;
                    linkedService?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numbers?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    sublabel?: T;
                    accent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processTimeline?:
          | T
          | {
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitLayout?:
          | T
          | {
              imageSide?: T;
              eyebrow?: T;
              title?: T;
              content?: T;
              action?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                  };
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        accentBlock?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              footnote?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        pricingGrid?:
          | T
          | {
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    priceSub?: T;
                    hot?: T;
                    badge?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    cta?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              heading?: T;
              meta?: T;
              logos?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              eyebrow?: T;
              quote?: T;
              name?: T;
              role?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        accordionFaq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              accent?: T;
              eyebrow?: T;
              title?: T;
              action?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                  };
              contacts?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  tier?: T;
  heroImage?: T;
  heroImageUrl?: T;
  body?: T;
  layout?:
    | T
    | {
        heroSplit?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              actions?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              image?: T;
              imageUrl?: T;
              imageCaption?: T;
              id?: T;
              blockName?: T;
            };
        heroFullbleed?:
          | T
          | {
              eyebrow?: T;
              meta?: T;
              statValue?: T;
              description?: T;
              background?: T;
              backgroundUrl?: T;
              tags?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        sectionHead?:
          | T
          | {
              number?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    image?: T;
                    imageUrl?: T;
                    tag?: T;
                    title?: T;
                    description?: T;
                    linkedService?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        numbers?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    sublabel?: T;
                    accent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processTimeline?:
          | T
          | {
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitLayout?:
          | T
          | {
              imageSide?: T;
              eyebrow?: T;
              title?: T;
              content?: T;
              action?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                  };
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        accentBlock?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              footnote?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        pricingGrid?:
          | T
          | {
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    priceSub?: T;
                    hot?: T;
                    badge?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    cta?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                              };
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              heading?: T;
              meta?: T;
              logos?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              eyebrow?: T;
              quote?: T;
              name?: T;
              role?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        accordionFaq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              accent?: T;
              eyebrow?: T;
              title?: T;
              action?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                  };
              contacts?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  nav?:
    | {
        /**
         * Optional icon before the link label.
         */
        icon?:
          | (
              | 'arrow-right'
              | 'arrow-up-right'
              | 'arrow-down'
              | 'plus'
              | 'minus'
              | 'x'
              | 'check'
              | 'chevron-down'
              | 'chevron-right'
              | 'chevron-left'
              | 'menu'
              | 'search'
              | 'external'
              | 'mail'
              | 'phone'
              | 'map-pin'
              | 'clock'
              | 'calendar'
              | 'user'
              | 'users'
              | 'file'
              | 'file-text'
              | 'folder'
              | 'code'
              | 'terminal'
              | 'git-branch'
              | 'zap'
              | 'cpu'
              | 'database'
              | 'server'
              | 'plug'
              | 'box'
              | 'layers'
              | 'grid'
              | 'layout'
              | 'sparkles'
              | 'bot'
              | 'message'
              | 'bell'
              | 'shield'
              | 'lock'
              | 'star'
              | 'trending-up'
              | 'bar-chart'
              | 'pie-chart'
              | 'compass'
              | 'settings'
              | 'play'
              | 'pause'
              | 'refresh'
              | 'download'
              | 'upload'
              | 'target'
              | 'flag'
              | 'link'
              | 'copy'
              | 'github'
              | 'filter'
              | 'more'
              | 'alert'
              | 'info'
              | 'eye'
            )
          | null;
        link?: {
          type?: ('internal' | 'external') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    link?: {
      type?: ('internal' | 'external') | null;
      newTab?: boolean | null;
      reference?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
      url?: string | null;
      label?: string | null;
      appearance?: ('primary' | 'secondary' | 'outline' | 'outline-accent' | 'ghost') | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Small mono-line under the logo (e.g. "TECH PARTNER · MARKETING").
   */
  brandTag?: string | null;
  tagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              icon?:
                | (
                    | 'arrow-right'
                    | 'arrow-up-right'
                    | 'arrow-down'
                    | 'plus'
                    | 'minus'
                    | 'x'
                    | 'check'
                    | 'chevron-down'
                    | 'chevron-right'
                    | 'chevron-left'
                    | 'menu'
                    | 'search'
                    | 'external'
                    | 'mail'
                    | 'phone'
                    | 'map-pin'
                    | 'clock'
                    | 'calendar'
                    | 'user'
                    | 'users'
                    | 'file'
                    | 'file-text'
                    | 'folder'
                    | 'code'
                    | 'terminal'
                    | 'git-branch'
                    | 'zap'
                    | 'cpu'
                    | 'database'
                    | 'server'
                    | 'plug'
                    | 'box'
                    | 'layers'
                    | 'grid'
                    | 'layout'
                    | 'sparkles'
                    | 'bot'
                    | 'message'
                    | 'bell'
                    | 'shield'
                    | 'lock'
                    | 'star'
                    | 'trending-up'
                    | 'bar-chart'
                    | 'pie-chart'
                    | 'compass'
                    | 'settings'
                    | 'play'
                    | 'pause'
                    | 'refresh'
                    | 'download'
                    | 'upload'
                    | 'target'
                    | 'flag'
                    | 'link'
                    | 'copy'
                    | 'github'
                    | 'filter'
                    | 'more'
                    | 'alert'
                    | 'info'
                    | 'eye'
                  )
                | null;
              link?: {
                type?: ('internal' | 'external') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  legal?:
    | {
        icon?:
          | (
              | 'arrow-right'
              | 'arrow-up-right'
              | 'arrow-down'
              | 'plus'
              | 'minus'
              | 'x'
              | 'check'
              | 'chevron-down'
              | 'chevron-right'
              | 'chevron-left'
              | 'menu'
              | 'search'
              | 'external'
              | 'mail'
              | 'phone'
              | 'map-pin'
              | 'clock'
              | 'calendar'
              | 'user'
              | 'users'
              | 'file'
              | 'file-text'
              | 'folder'
              | 'code'
              | 'terminal'
              | 'git-branch'
              | 'zap'
              | 'cpu'
              | 'database'
              | 'server'
              | 'plug'
              | 'box'
              | 'layers'
              | 'grid'
              | 'layout'
              | 'sparkles'
              | 'bot'
              | 'message'
              | 'bell'
              | 'shield'
              | 'lock'
              | 'star'
              | 'trending-up'
              | 'bar-chart'
              | 'pie-chart'
              | 'compass'
              | 'settings'
              | 'play'
              | 'pause'
              | 'refresh'
              | 'download'
              | 'upload'
              | 'target'
              | 'flag'
              | 'link'
              | 'copy'
              | 'github'
              | 'filter'
              | 'more'
              | 'alert'
              | 'info'
              | 'eye'
            )
          | null;
        link?: {
          type?: ('internal' | 'external') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        icon?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandTag?: T;
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              icon?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  legal?:
    | T
    | {
        icon?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}